### ISSUE TITLE
Thank You Note & Minor Suggested Changes

### ISSUE THREAD

**Issue by AFg6K7h4fhy2** [xiaziyna/PyStarshade#2]
(1) Thank you for developing `PyStarshade`.
(2) Context: I am interested in learning more data science / computational modeling for research in astronomy. 
(3) I hope, at some point, to provide user feedback for `PyStarshade`.
(4) I come with two minor, Python-based recommendations: `pre-commit` and `poetry`.
(5) Feel free to ignore the following minor suggestions:

<details markdown=1>
<summary>
One Minor Suggestion...
</summary>

__Poetry__

Consider using `poetry` (<https://python-poetry.org/>) for dependency management. 

> Poetry is a tool for dependency management and packaging in Python. It allows you to declare the libraries your project depends on and it will manage (install/update) them for you. Poetry offers a lockfile to ensure repeatable installs, and can build your project for distribution.

Once users clone your repository, users only have 

* to have `poetry` installed
* to write `poetry install` to use your package.

Example `pyproject.toml` file:

```yaml
[tool.poetry]
name = "forecasttools"
version = "0.0.1"
description = "Python package for common pre- and post-processing operations done by CFA Predict for short term forecasting, nowcasting, and scenario modeling."
authors = ["CFA"]
license = "Apache-2.0"
readme = "README.md"
packages = [{include = "forecasttools"}]
repository = "https://github.com/CDCgov/forecasttools-py/"
keywords = ["forecasting", "infrastructure", "infectious-disease-modeling", "python"]

[tool.poetry.dependencies]
python = "^3.12"
arviz = "^0.20.0"
polars = "^1.8.2"
xarray = "^2024.9.0"
matplotlib = "^3.9.2"
epiweeks = "^2.3.0"

[tool.poetry.group.dev.dependencies]
pre-commit = "^3.8.0"
ipykernel = "^6.29.5"
numpyro = "^0.15.3"
diffrax = "^0.6.0"
patsy = "^0.5.6"
nbformat = "^5.10.4"
nbclient = "^0.10.0"
jupyter = "^1.1.1"

[tool.poetry.group.test.dependencies]
pytest = "^8.3.3"

[tool.poetry.urls]
"Repository Issues" = "https://github.com/CDCgov/forecasttools-py/issues"
"CDCgov Repositories" = "https://github.com/CDCgov"
"Package That Will Use Forecasttools" = "https://github.com/CDCgov/pyrenew-hew"
"Poetry Pyproject Page" = "https://python-poetry.org/docs/pyproject/"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
```
</details>

<details markdown=1>
<summary>
Another Minor Suggestion...
</summary>

__Pre-Commit__

Consider using `pre-commit` (<https://pre-commit.com/>) for linting and ensuring your Python code adheres to PEP guidelines.

> Git hook scripts are useful for identifying simple issues before submission to code review. We run our hooks on every commit to automatically point out issues in code such as missing semicolons, trailing whitespace, and debug statements. By pointing these issues out before code review, this allows a code reviewer to focus on the architecture of a change while not wasting time with trivial style nitpicks.
>
> As we created more libraries and projects we recognized that sharing our pre-commit hooks across projects is painful. We copied and pasted unwieldy bash scripts from project to project and had to manually change the hooks to work for different project structures.
> 
> We believe that you should always use the best industry standard linters. Some of the best linters are written in languages that you do not use in your project or have installed on your machine. For example scss-lint is a linter for SCSS written in Ruby. If you’re writing a project in node you should be able to use scss-lint as a pre-commit hook without adding a Gemfile to your project or understanding how to get scss-lint installed.
> 
> We built pre-commit to solve our hook issues. It is a multi-language package manager for pre-commit hooks. You specify a list of hooks you want and pre-commit manages the installation and execution of any hook written in any language before every commit. pre-commit is specifically designed to not require root access. If one of your developers doesn’t have node installed but modifies a JavaScript file, pre-commit automatically handles downloading and building node to run eslint without root.

Upon installing `pre-commit` and then creating the files `.pre-commit-config.yaml` and `./.github/workflows/pre-commit.yaml`, and typing `pre-commit install` in your repository, `pre-commit` will run a series of checks each time you attempt to `git commit -m "message"`. If there are failed outcomes, you can run `pre-commit run --all-files` or redo `git add -A` before again doing `git commit -m "message"`. 

Example Of Successful Tests:

<img width="956" alt="Screenshot 2024-12-10 at 16 39 22" src="https://github.com/user-attachments/assets/99ed94bf-6255-4d32-bb17-0a2df312a85c">

Example Of `.pre-commit-config.yaml` File From One Of My Repositories:

```yaml
################################################################################
# OVERVIEW
################################################################################
# The following contains the pre-commit hooks for this repository, which are
# likely a modified version of the author's (AFg6K7h4fhy2) repository template.
#
# Links:
#
# Pre-commit: https://pre-commit.com/
# The author's template: https://github.com/AFg6K7h4fhy2/AFg6K7h4fhy2-Template
# Supported hooks: https://github.com/pre-commit/pre-commit-hooks
repos:
################################################################################
# GENERAL
################################################################################
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
    # prevent giant files from being committed.
    -   id: check-added-large-files
        args: ["--maxkb=10000"]
    # simply check whether files parse as valid
    # python
    -   id: check-ast
    # check for files with names that would
    # conflict on a case-insensitive filesystem
    # like MacOS HFS+ or Windows FAT.
    -   id: check-case-conflict
    # checks for a common error of placing
    # code before the docstring.
    -   id: check-docstring-first
    # attempts to load all yaml files to
    # verify syntax.
    -   id: check-yaml
        # allow yaml files which use the
        # multi-document syntax
        args: ["--allow-multiple-documents"]
    # attempts to load all TOML files to
    # verify syntax.
    -   id: check-toml
    # makes sure files end in a newline and
    # only a newline.
    -   id: end-of-file-fixer
    # replaces or checks mixed line ending.
    -   id: mixed-line-ending
    # verifies that test files are named
    # correctly.
    -   id: name-tests-test
        # ensure tests match test_.*\.py
        args: ["--pytest-test-first"]
    # checks that all your JSON files are pretty.
    # "Pretty" here means that keys are sorted
    # and indented.
    -   id: pretty-format-json
        # automatically format json files;
        # when autofixing, retain the original
        # key ordering (instead of sorting
        # the keys)
        args: ["--autofix", "--no-sort-keys"]
    # trims trailing whitespace.
    -   id: trailing-whitespace
    # checks that non-binary executables have
    # a proper shebang.
    -   id: check-executables-have-shebangs
        files: \.sh$
    # checks for the existence of private keys.
    -   id: detect-private-key
################################################################################
# PYTHON
################################################################################
-   repo: https://github.com/psf/black-pre-commit-mirror
    rev: 24.10.0
    hooks:
    -   id: black
        args: ["--line-length", "79"]
        language_version: python3
-   repo: https://github.com/PyCQA/isort
    rev: 5.13.2
    hooks:
    -   id: isort
        args: ["--profile", "black", "--line-length", "79"]
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.2
    hooks:
      - id: ruff
        args: ["--ignore=E741", "--ignore=E731", "--fix"]
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.13.0
    hooks:
      - id: mypy
################################################################################
# SPELLING
################################################################################
-   repo: https://github.com/crate-ci/typos
    rev: typos-dict-v0.11.37
    hooks:
    -   id: typos
        args: ["--force-exclude"]
```

The `typos` `pre-commit` hook is nice in that it finds common spelling errors. If you want to use `typos`, you will need a `_typos.toml` file. For example, this is the one I have associated with the about `pre-commit` config file.

```
[default]
extend-ignore-identifiers-re = [
    "AttributeID.*Supress.*",
]

[default.extend-identifiers]
AttributeIDSupressMenu = "AttributeIDSupressMenu"

[default.extend-words]
# words that should not be corrected
AFg6K7h4fhy2 = "AFg6K7h4fhy2"
dot_acn = ".acn"
dot_fot = ".fot"
dot_ist = ".ist"

[files]
extend-exclude = [
    ".gitignore",
    ".pre-commit-config.yaml",
    "./.github/ISSUE_TEMPLATE/*.md"]
``` 
</details>

<details markdown=1>
<summary> 
One Final Suggestion...
</summary>

Consider adding, to your `.gitignore`, some of the content in the default Python `.gitignore` found here <https://github.com/github/gitignore/blob/main/Python.gitignore>. 

</details>

(6) If so desired, I can implement these above recommendations in a PR; your approval is the output node.
(7) Again, thank you, and may this repository live a long and useful life!

_This issue may be deleted once read. Any accepted suggestions can be addressed in other issues._
